port: 23333
session:
  name: jh-ucenter-session-id
  secret_key: qebmvxrkyauxtuhk
db:
  type: postgres
  host: 127.0.0.1
  port: 5432
  user: username
  password: password
  dbname: dbname
client:
  - id: test
    secret: testsecret
    name: 测试应用
    domain: http://localhost:9094
    scope:
      - userinfo
